/** Sprechblasen- und Menuetexte (de/en). `pick` waehlt bei Listen eine Variante. */

export const Texts = {
  de: {
    hello: "hallo!",
    fed: ["mjam", "lecker!", "nom nom"],
    overfed: "*rülps*",
    played: ["nochmal!", "juhu", "tadaa!"],
    petted: ["♥", "hihi", "mehr!"],
    grumbled: "grmpf...",
    cleaned: "danke!",
    healed: "viel besser",
    sick: "mir ist schlecht",
    hungry: ["Hunger!", "wann gibt es essen?"],
    feeding_time: ["essen?", "ich hätte da hunger"],
    appointment_soon: (d) => `${d.title}\nin ${d.minutes} min`,
    welcome_home: "willkommen zurück!",
    fell_asleep: "gute nacht",
    woke_up: "guten morgen!",
    evolved: "ich bin gewachsen!",
    too_tired: "zu müde...",
    tummy_ache: "bauchweh",
    medicine_refused: "bäh!",
    fainted: "...",
    revived: "wo bin ich?",
    hatched: "hallo welt!",
    died: "auf wiedersehen",
    hide: ["psst", "hier ist niemand", "..."],
    boo: "BUH!",
    trick: ["tadaa!", "hui", "nochmal?"],
    rain: "platsch",
    sunny: ["ahh, sonne", "eis?"],
    stressed: ["so viel zu tun", "keine zeit!"],
    lonely: ["wo sind alle?", "hallo?"],
    bored: ["laaangweilig", "spielt jemand?"],
    linger: ["hm", "schön hier", "*gähn*", "..."],
    built: "fertig gebaut!",
    vacation: ["urlaub!", "🍹", "so entspannt"],
    vacation_started: "ich mach urlaub!",
    vacation_ended: "wieder da!",
    visit_house: ["mein Haus", "daheim"],
    visit_swing: ["juhu!", "höher!"],
    visit_flowers: ["hübsch", "*gieß*"],
    visit_snowman: ["brrr", "hallo Schneemann"],
    visit_golf: ["fore!", "abschlag!"],
    golf_in: ["eingelocht!", "und drin!"],
    music: "musik!",
    poop_hint: "hier stinkt es",
    menu: { meal: "Füttern", snack: "Snack", treat: "Leckerli", play: "Spielen", pet: "Streicheln", clean: "Putzen", medicine: "Medizin" },
    stats: { hunger: "Sättigung", happiness: "Laune", energy: "Energie", health: "Gesundheit", age: "Alter", stage: "Stufe", feeds: "Fütterungen", top: "Am meisten gefüttert" },
    stage: { egg: "Ei", baby: "Baby", child: "Kind", teen: "Teenager", adult: "Erwachsen", senior: "Senior" },
    days: "Tage",
  },
  en: {
    hello: "hello!",
    fed: ["yum", "tasty!", "nom nom"],
    overfed: "*burp*",
    played: ["again!", "yay", "tadaa!"],
    petted: ["♥", "hehe", "more!"],
    grumbled: "grmpf...",
    cleaned: "thanks!",
    healed: "much better",
    sick: "I feel sick",
    hungry: ["hungry!", "when is dinner?"],
    feeding_time: ["food?", "I'm a bit hungry"],
    appointment_soon: (d) => `${d.title}\nin ${d.minutes} min`,
    welcome_home: "welcome back!",
    fell_asleep: "good night",
    woke_up: "good morning!",
    evolved: "I grew up!",
    too_tired: "too tired...",
    tummy_ache: "tummy ache",
    medicine_refused: "yuck!",
    fainted: "...",
    revived: "where am I?",
    hatched: "hello world!",
    died: "goodbye",
    hide: ["psst", "nobody here", "..."],
    boo: "BOO!",
    trick: ["tadaa!", "whee", "again?"],
    rain: "splash",
    sunny: ["ahh, sun", "ice cream?"],
    stressed: ["so much to do", "no time!"],
    lonely: ["where is everyone?", "hello?"],
    bored: ["booooring", "anyone playing?"],
    linger: ["hm", "nice here", "*yawn*", "..."],
    built: "all built!",
    vacation: ["vacation!", "🍹", "so relaxed"],
    vacation_started: "I'm on vacation!",
    vacation_ended: "back at it!",
    visit_house: ["my house", "home"],
    visit_swing: ["wheee!", "higher!"],
    visit_flowers: ["pretty", "*water*"],
    visit_snowman: ["brrr", "hi snowman"],
    visit_golf: ["fore!", "tee off!"],
    golf_in: ["sunk it!", "in the hole!"],
    music: "music!",
    poop_hint: "it smells here",
    menu: { meal: "Feed", snack: "Snack", treat: "Treat", play: "Play", pet: "Pet", clean: "Clean", medicine: "Medicine" },
    stats: { hunger: "Fullness", happiness: "Happiness", energy: "Energy", health: "Health", age: "Age", stage: "Stage", feeds: "Feedings", top: "Top feeder" },
    stage: { egg: "Egg", baby: "Baby", child: "Child", teen: "Teen", adult: "Adult", senior: "Senior" },
    days: "days",
  },
  pick(lang, key, data) {
    const table = Texts[lang] || Texts.de;
    const value = table[key] ?? Texts.de[key];
    if (typeof value === "function") return value(data || {});
    return Array.isArray(value) ? value[Math.floor(Math.random() * value.length)] : value;
  },
};
